# Generated by Django 4.2.9 on 2026-06-03 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_id", models.IntegerField()),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=14)),
                ("status", models.CharField(choices=[("PENDING","Chờ thanh toán"),("PAID","Đã thanh toán"),("SHIPPED","Đang giao"),("DELIVERED","Đã giao"),("PAYMENT_FAILED","Thanh toán thất bại"),("CANCELLED","Đã hủy")], default="PENDING", max_length=50)),
                ("shipping_address", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "orders", "ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_id", models.IntegerField()),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="orders.order")),
            ],
            options={"db_table": "order_item"},
        ),
    ]
