# Generated by Django 4.2.9 on 2026-06-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.CharField(blank=True, default='', help_text='Nghề nghiệp — phục vụ knowledge graph (Neo4j)', max_length=120),
        ),
    ]
